project:
  type: website

website:
  title: "ms914.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: klausuren.qmd
        text: Klausuren HM1 - HM4
      - href: klausuren_latex.qmd
        text: Latex HM1 - HM4  
      - href: HM_solutions.qmd
        text: Lösungen HM1 - HM4
      - href: karteikarten.qmd
        text: Karteikarten
      - about.qmd
      - hm3_codecopy.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



