project:
  type: website

website:
  title: "ms914.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: klausuren.qmd
        text: Klausuren  
      - href: HM_solutions.qmd
        text: Lösungen
      - href: karteikarten.qmd
        text: Karteikarten
      - href: hm3_codecopy.qmd
        text: code
      - href: hm3_klausur_ws2425.qmd
        text: Klausur WS 24/25
      - href: hm3_python.qmd
        text: Sympy
      - href: Klausuren_HM_3C.qmd
        text: Klausuren_sympy
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



