---
title: "Exam Questions"
format: html
---

# HM3 Exam Questions

## Aufgabe 1 (10 Punkte)

**a)** Lösen Sie das Anfangswertproblem  
$$
x' = t\,x^2 + t,\quad x(0)=0,
$$
Hinweis: $\arctan'(x)=\frac{1}{1+x^2}$.

**b)** Betrachten Sie die Differentialgleichung
$$
2tx^3-2t+3t^2x^2x'=0,\quad x(1)=0.
$$
(i) Zeigen Sie, dass die DGL exakt ist.  
(ii) Geben Sie eine Funktion $\Phi=\Phi(t,x)$ an, so dass $\Phi_t(t,x)+\Phi_x(t,x)\dot x=0$.  
(iii) Geben Sie die Lösung des Anfangswertproblems an. Gegen welchen Wert konvergiert die Lösung für $t \rightarrow \infty$.

## Aufgabe 2 (10 Punkte)

Gegeben ist das lineare System
$$
\dot x=\begin{pmatrix}3 & -1\\5 & -1\end{pmatrix}x.
$$
**a)** Geben Sie ein reelles Fundamentalsystem an.  
**b)** Geben Sie die allgemeine reelle Lösung des Anfangswertproblems $\dot x=Ax+b$ mit  
$$
b=\begin{pmatrix}1\\0\end{pmatrix}
$$
an.

## Aufgabe 3 (10 Punkte)

Gegeben sei die partielle Differentialgleichung
$$
2u_t-u_{xx}=0,
$$
mit $x\in[0,\pi]$ und $t>0$.

**a)** Klassifizieren Sie die Differentialgleichung (elliptisch, parabolisch, hyperbolisch).  
**b)** Bestimmen Sie die Koeffizienten der Fouriereihe der ungeraden periodisch fortgesetzten Funktion  
$$
f(x)=1\quad \text{für } x\in [0,\pi].
$$  
**c)** Bestimmen Sie für alle $k\in\mathbb{N}$ eine Lösung der PDE mit der Anfangsbedingung
$$
u(0,x)=\sin(kx)\quad (x\in[0,\pi]),
$$
die die Randbedingungen $u(t,0)=u(t,\pi)=0,\;t>0$ erfüllt.

## Aufgabe 4 (10 Punkte)

Gegeben sei das parameterabhängige Vektorfeld 
$$
F:\mathbb{R}^3\to\mathbb{R}^3,\quad F=\begin{pmatrix} x\frac{y^3}{3}\\x^2\Bigl(z^2+\frac{y^2}{2}\Bigr)-\alpha x^2z^2\\(1-\alpha)2x^2yz+z^2 \end{pmatrix},
$$
und der Weg
$$
\gamma:[0,1]\to\mathbb{R}^3,\quad \gamma(t)=\begin{pmatrix}1-t^2\\t^2\\t\end{pmatrix}.
$$
**a)** Bestimmen Sie alle $\alpha\in\mathbb{R}$, sodass $F$ ein Potential besitzt.  
**b)** Geben Sie für $\alpha=1$ ein Potential an.  
**c)** Berechnen Sie für $\alpha=1$ das Kurvenintegral 2. Art von $F$ entlang $\gamma$.

## Aufgabe 5 (10 Punkte)

Es sei 
$$
\gamma(u)=(e^u-1,0,u)^T,\quad u\in[0,1],
$$
ein planarer Weg in der x‑z-Ebene. Mit $A$ bezeichnen wir die Rotationsfläche, die entsteht, wenn $\gamma$ um die z‑Achse rotiert wird.

Gegeben sei außerdem das Vektorfeld 
$$
F:\mathbb{R}^3\to\mathbb{R}^3,\quad F(x,y,z)=\begin{pmatrix} x+y\\y-x\\2 \end{pmatrix}.
$$
**a)** Geben Sie eine Parametrisierung $f(u,v)$ der Fläche $A$ an.  
**b)** Bestimmen Sie Tangentialvektoren und den Normalenvektor an $A$.  
**c)** Bestimmen Sie das Oberflächenintegral 2. Art $\int_A F\cdot dn$.

## Aufgabe 6 (10 Punkte)

Es sei 
$$
K=\{(x,y,z)^T\in\mathbb{R}^3 : x^2+y^2+z^2\leq4,\; y\geq0,\; z\geq0
$$
das Kugelsegment und $\partial K$ die Vereinigung aller Oberflächen des Segments.  
Weiterhin sei 
$$
F:\mathbb{R}^3\to\mathbb{R}^3,\quad F(x,y,z)=\begin{pmatrix} x-y\\x+y\\z+xy \end{pmatrix}.
$$
**a)** Parametrisieren Sie das Volumen in Kugelkoordinaten.  
**b)** Berechnen Sie den Fluss $\int_{\partial K}F\cdot n\,dS$, wobei $n$ die nach außen gerichtete Normale ist.  
**c)** Berechnen Sie $\int_{\partial K}\operatorname{rot}(F)\cdot n\,dS$.  
**d)** Berechnen Sie mit dem Satz von Stokes das Integral $\int_{\partial K\setminus B}rot F\cdot n\,dS$, wobei $B$ der Boden des Kugelsegments in der (x‑y)-Ebene ist.
